name: Gitflow Release

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Gitflow action to perform'
        required: true
        type: choice
        options:
          - release-start
          - release-finish
      version:
        description: 'Release version (for release-start and release-finish, e.g., 1.0.0)'
        required: false

jobs:
  call-gitflow-release:
    uses: dataliquid/github-actions/.github/workflows/gitflow-release.yml@master
    with:
      action: ${{ inputs.action }}
      version: ${{ inputs.version }}
      java-version: '11'
      java-distribution: 'temurin'
    secrets: inherit